# Generated by Django 6.0 on 2026-01-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomboid_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='mood',
            field=models.CharField(choices=[('Angry', 'Angry'), ('Bored', 'Bored'), ('Concentrating', 'Concentrating'), ('Dead', 'Dead'), ('Discomfort', 'Discomfort'), ('Dizzy', 'Dizzy'), ('Drunk', 'Drunk'), ('Exhausted', 'Exhausted'), ('Happy', 'Happy'), ('Hungover', 'Hungover'), ('Ill', 'Ill'), ('Nauseous', 'Nauseous'), ('NoxiousSmell', 'Noxious Smell'), ('Pained', 'Pained'), ('Panicked', 'Panicked'), ('Sad', 'Sad'), ('Scared', 'Scared'), ('Sleepy', 'Sleepy'), ('Stressed', 'Stressed'), ('Zombified', 'Zombified')], default='Bored'),
        ),
    ]
